import type { RealProviderSmokeTarget } from "@/domain/ops/real-provider-smoke";

export const REAL_PROVIDER_SMOKE_TARGETS: RealProviderSmokeTarget[] = [
  {
    id: "kis_quote_kr_005930",
    providerId: "kis",
    capability: "quote",
    method: "GET",
    endpoint: "/api/market/quote?symbol=005930&region=KR&providerId=kis",
    symbol: "005930",
    region: "KR",
    requiresApiKey: true,
    expectedWithoutKey: "api_required_allowed",
    expectedWithKey: "data_available",
  },
  {
    id: "kis_ohlcv_kr_005930",
    providerId: "kis",
    capability: "ohlcv",
    method: "GET",
    endpoint: "/api/market/ohlcv?symbol=005930&region=KR&range=1M&interval=1D&providerId=kis",
    symbol: "005930",
    region: "KR",
    requiresApiKey: true,
    expectedWithoutKey: "api_required_allowed",
    expectedWithKey: "data_available",
  },
  {
    id: "opendart_disclosures_kr_00126380",
    providerId: "opendart",
    capability: "filings",
    method: "GET",
    endpoint: "/api/opendart/disclosures?corpCode=00126380&pageNo=1&pageCount=10",
    symbol: "005930",
    region: "KR",
    requiresApiKey: true,
    expectedWithoutKey: "api_required_allowed",
    expectedWithKey: "data_available",
  },
  {
    id: "opendart_financials_kr_00126380",
    providerId: "opendart",
    capability: "financials",
    method: "GET",
    endpoint: "/api/opendart/financials?corpCode=00126380&year=2025",
    symbol: "005930",
    region: "KR",
    requiresApiKey: true,
    expectedWithoutKey: "api_required_allowed",
    expectedWithKey: "not_supported_allowed",
  },
  {
    id: "fmp_quote_us_aapl",
    providerId: "fmp_free",
    capability: "quote",
    method: "GET",
    // providerId param ensures only FMP is called — prevents generic priority-chain fallback
    endpoint: "/api/market/quote?symbol=AAPL&region=US&providerId=fmp_free",
    symbol: "AAPL",
    region: "US",
    requiresApiKey: true,
    expectedWithoutKey: "not_supported_allowed",
    expectedWithKey: "data_available",
  },
  {
    id: "fmp_ohlcv_us_aapl",
    providerId: "fmp_free",
    capability: "ohlcv",
    method: "GET",
    endpoint: "/api/market/ohlcv?symbol=AAPL&region=US&range=1M&interval=1D&providerId=fmp_free",
    symbol: "AAPL",
    region: "US",
    requiresApiKey: true,
    expectedWithoutKey: "not_supported_allowed",
    expectedWithKey: "data_available",
  },
  {
    id: "finnhub_quote_us_aapl",
    providerId: "finnhub_free",
    capability: "quote",
    method: "GET",
    endpoint: "/api/market/quote?symbol=AAPL&region=US&providerId=finnhub_free",
    symbol: "AAPL",
    region: "US",
    requiresApiKey: true,
    expectedWithoutKey: "not_supported_allowed",
    expectedWithKey: "data_available",
  },
  {
    id: "finnhub_ohlcv_us_aapl",
    providerId: "finnhub_free",
    capability: "ohlcv",
    method: "GET",
    endpoint: "/api/market/ohlcv?symbol=AAPL&region=US&range=1M&interval=1D&providerId=finnhub_free",
    symbol: "AAPL",
    region: "US",
    requiresApiKey: true,
    expectedWithoutKey: "not_supported_allowed",
    expectedWithKey: "data_available",
  },
  {
    id: "alpha_vantage_quote_us_aapl",
    providerId: "alpha_vantage_free",
    capability: "quote",
    method: "GET",
    // providerId param ensures only Alpha Vantage is called — prevents fallback mismatch
    endpoint: "/api/market/quote?symbol=AAPL&region=US&providerId=alpha_vantage_free",
    symbol: "AAPL",
    region: "US",
    requiresApiKey: true,
    expectedWithoutKey: "not_supported_allowed",
    expectedWithKey: "data_available",
  },
  {
    // P1-2: provider_health is a system/registry health check, not KIS-specific.
    // It verifies the system provider readiness endpoint, using "system" attribution.
    id: "provider_health",
    providerId: "system",
    capability: "provider_health",
    method: "GET",
    endpoint: "/api/ops/provider-readiness",
    symbol: null,
    region: null,
    requiresApiKey: false,
    expectedWithoutKey: "data_available",
    expectedWithKey: "data_available",
  },
];
